# Generated by Django 4.1.1 on 2022-09-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='Загрузите фото в jpeg или png формате', upload_to='products/', verbose_name='Изображение'),
        ),
    ]
