# Generated by Django 4.1.1 on 2022-09-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('image', models.ImageField(help_text='Загрузите фото в jpeg или png формате', upload_to='products/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, help_text='Пока что можно не заполнять', null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.BooleanField(default=False, help_text='Если вы поставите здесь галочку, то это предложение не будет отображаться на сайте', verbose_name='Черновик')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
