# Generated by Django 4.1.1 on 2022-09-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_description_alter_news_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='mailing',
            field=models.BooleanField(default=False, help_text='Если вы поставите здесь галочку, то все подписчики получат эту новость на почту', verbose_name='Рассылка'),
        ),
    ]
